apiVersion: apps/v1
kind: Deployment
metadata: 
  name: php-apache
  labels:
    ENV: prod
    run: php-apache
  namespace: default
spec:
  selector:
    matchLabels:
      ENV: prod
      run: php-apache
  template:
    metadata:
      name: php-apache
      labels:
        ENV: prod
        run: php-apache
    spec:
      containers:
        - name: php-apache
          image: registry.k8s.io/hpa-example
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    ENV: prod
    run: php-apache
  namespace: default
spec:
  selector:
    run: php-apache
  ports:
    - port: 80
      targetPort: 80
    

