apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  namespace: nginx
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: nginx1-pod
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx-con
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: my-volume

      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: local-pvc




        
