apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: default
  labels:
    app: demo
spec:
  containers:
    - name: deme-con
      image: httpd
      ports:
        - containerPort: 80
      nodeName: worker02.server.vm



