apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-with-db
  labels:
    app: my-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      name: webapp-with-db
      labels:
        app: my-webapp
    spec:
      containers:
      - name: webapp
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-srv
  labels:
    app: my-webapp-srv
spec:
  type: NodePort
  selector:
    app: my-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31100   

