apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deploy
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.28.0
        ports:
        - containerPort: 80
