apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    ENV: dev
spec:
  containers:
    - name: nginx
      image: nginx
    - name: redis
      image: redis
    - name: nginx-second
      image: nginx:1.28.0-alpine-slim


