apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-demo
  labels:
    app: demo
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels:
        env: LB
    spec:
      containers:
      - name: nginx-con
        image: nginx:latest
        ports:
        - containerPort: 80


