apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: polinux/stress
    command: ["stress"]
    args: ["--vm","1","--vm-bytes","250M","--vm-hang","1"]
    resources:
      requests:
        memory: "150Gi"
        cpu: "100m"
      limits:
        memory: "250Gi"
        cpu: "150m"
