apiVersion: v1 
kind: Pod
metadata:
  name: stress-pod
  namespace: default
  labels:
    app: stress-test
spec:
  containers:
  - name: stress-container
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
    resources:
      requests:
        memory: "1000Mi"
      limits:
        memory: "2000Mi"
    
 
