apiVersion: v1
kind: Pod
metadata:
   name: flask-app
spec:
   containers:
   - name: flask-mongodb
     image: mahinraza556/flask-app:crud-with-mongodb
     ports:
     - containerPort: 5000
     imagePullPolicy: Always
     env:
       - name: DB_HOST
         valueFrom:
           configMapKeyRef:
             name: flask-app-config
             key: DB_HOST
       - name: DB_NAME
         valueFrom:
           configMapKeyRef:
             name: flask-app-config
             key: DB_NAME
       - name: DB_USER
         valueFrom:
           secretKeyRef:
             name: flask-app-secret
             key: DB_USER
       - name: DB_PASSWORD
         valueFrom:
           secretKeyRef:
             name: flask-app-secret
             key: DB_PASSWORD
     livenessProbe:
       httpGet:
         path: /items
         port: 5000
       initialDelaySeconds: 15 # Allow time for MongoDB to start
       periodSeconds: 10
       timeoutSeconds: 5
       failureThreshold: 2
     readinessProbe:
       httpGet:
         path: /items
         port: 5000
       initialDelaySeconds: 15 # Allow time for MongoDB to start
       periodSeconds: 10
       timeoutSeconds: 5
       failureThreshold: 2

   - name: mongodb-con
     image: mongo:6.0.26
     ports:
     - containerPort: 27017
     imagePullPolicy: Always
     env:
       - name: MONGO_INITDB_DATABASE
         valueFrom:
           configMapKeyRef:
             name: flask-app-config
             key: DB_NAME
       - name: MONGO_INITDB_ROOT_USERNAME
         valueFrom:
           secretKeyRef:
             name: flask-app-secret
             key: DB_USER
       - name: MONGO_INITDB_ROOT_PASSWORD
         valueFrom:
           secretKeyRef:
             name: flask-app-secret
             key: DB_PASSWORD
     readinessProbe:
       tcpSocket:
         port: 27017
       initialDelaySeconds: 10 
       periodSeconds: 5      
       timeoutSeconds: 3     
       failureThreshold: 3   