#rc.yaml

apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 3                 #Specifies the desired number of pod replicas (in this case, 3).
  selector:                   #Defines how the Replication Controller identifies which pods it manages.
    app: myapp 
  template:                   # Defines the pod template used for creating new pod replicas.
    metadata: 
      labels:                 #Labels applied to the pods
        app: myapp
    spec:
      containers:             #Container specification for the pods, including image and ports.
      - name: myapp-container
        image: nginx:latest
        ports:
        - containerPort: 80