apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: nginx-daemonset
  namespace: default
spec: 
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: nginx1-daemon-pod
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx-con
        image: nginx:latest
        ports:
          - containerPort: 80


        
