apiVersion: v1
kind: DaemonSet
metadata:
  name: splunk-monitoring-agent
spec:
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
      - name: splunk-monitoring-agent
        image: splunk:latest
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchFields:
            - key: metadata.name
              operator: In
              values:
              - target-host-name
