apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    app: demo
    type: frontend
spec:
  containers:
  - name: nginx-con1
    image: nginx:latest
    ports:
      - containerPort: 80
      - containerPort: 443
