apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-demo
  labels:
    env: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      env: demo
  template:
    metadata:
      name: nginx-pod
      labels:
        env: demo
    spec:
      containers:
      - name: nginx-con
        image: nginx:1.28
        ports:
        - containerPort: 80


