apiVersion: v1
kind: Pod
metadata:
  name: downward-demo
  labels:
    app: myapp
  annotations:
    description: "Demo Pod for Downward API"
spec:
  containers:
    - name: demo-container
      image: busybox
      command: ["sh", "-c"]
      args:
      - |-
        while true; do
          echo "Env Vars:";
          echo "Pod: $MY_POD_NAME, Namespace: $MY_POD_NAMESPACE, Node: $MY_NODE_NAME";
          echo "CPU Request: $MY_CPU_REQUEST, Mem Limit: $MY_MEM_LIMIT";
          echo "Labels:"; cat /etc/podinfo/labels;
          echo "Annotations:"; cat /etc/podinfo/annotations;
          sleep 20;
        done;
      env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              resource: requests.cpu
        - name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations

# https://kubernetes.io/docs/concepts/workloads/pods/downward-api/#available-fields