apiVersion: v1
kind: Pod
metadata:
  name: webapp-init-sidecar
spec:
  # INIT CONTAINER
  initContainers:
    - name: init-config
      image: busybox
      command: ['sh', '-c', 'echo "Initializing app config" > /work/config.txt']
      volumeMounts:
        - name: workdir
          mountPath: /work

  # MAIN + SIDECAR CONTAINERS
  containers:
    - name: webapp
      image: nginx
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
    - name: log-sidecar
      image: busybox
      command: ['sh', '-c', 'tail -f /usr/share/nginx/html/config.txt']
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html

  volumes:
    - name: workdir
      emptyDir: {}
